#!/bin/sh
### BEGIN INIT INFO
# Provides:          childwaf
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Should-Start:      dnsmasq
# Should-Stop:       dnsmasq
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: childwaf internet filter
# Description:       Per-child internet access control using iptables,
#                    ipset, and dnsmasq on Devuan / sysvinit systems.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=childwaf
DESC="childwaf internet filter"
DAEMON=/usr/local/sbin/childwaf
DEFAULTS=/etc/default/childwaf

. /lib/lsb/init-functions

# Load site-specific defaults if present
[ -r "$DEFAULTS" ] && . "$DEFAULTS"

test -x "$DAEMON" || { echo "$DAEMON not found or not executable"; exit 5; }

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        "$DAEMON" start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        "$DAEMON" stop
        log_end_msg $?
        ;;
    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        "$DAEMON" restart
        log_end_msg $?
        ;;
    reload|force-reload)
        log_daemon_msg "Reloading $DESC configuration" "$NAME"
        "$DAEMON" reload
        log_end_msg $?
        ;;
    status)
        "$DAEMON" status
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
